### ISSUE TITLE
Error on view initialization: 

### ISSUE THREAD

**Issue by rastafan** [heidji/ionic4-hidenav#4]
Hi,

thanks for this component, it looks awesome and very promising.
Unfortunately, i run in an issue when using hidenav with super-tabs.
It was working in the beginning, then suddenly it stopped after building for android.
I was trying it using `ionic serve`, so maybe stopping and restarting it triggered this error. I don't know what could possibly break it.

Anyway, right now it appears as if hidenav is initialized before super-tabs is, resulting in this error:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'tabChange' of undefined
TypeError: Cannot read property 'tabChange' of undefined
    at HidenavShTabscontentDirective.ngAfterViewInit (ionic4-hidenav.js:1455)
    at callProviderLifecycles (core.js:28206)
    at callElementProvidersLifecycles (core.js:28171)
    at callLifecycleHooksChildrenFirst (core.js:28153)
    at checkAndUpdateView (core.js:38386)
    at callViewAction (core.js:38742)
    at execComponentViewsAction (core.js:38670)
    at checkAndUpdateView (core.js:38383)
    at callWithDebugContext (core.js:39716)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:39299)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
```

This is the piece of code from hidenav throwing this error (ionic4-hidenav.js:1455):
```
class HidenavShTabscontentDirective {
    /**
     * @param {?} el
     * @param {?} contentElem
     * @param {?} globals
     */
    constructor(el, contentElem, globals) {
        this.el = el;
        this.contentElem = contentElem;
        this.globals = globals;
    }
    /**
     * @return {?}
     */
    ngAfterViewInit() {
        this.name = this.globals.requestName();
        this.contentElem.nativeElement.setAttribute('hidenav-sh-tabscontent', this.name);
        $('hidenav-stretchheader', $(this.contentElem.nativeElement).parents().get().find((/**
         * @param {?} itm
         * @return {?}
         */
        itm => $(itm).find('[hidenav-stretchheader]').length))).attr('hidenav-sh-header', this.name);
        if (this.name) {
            if (typeof this.globals.data[this.name] == 'undefined' || this.globals.data[this.name] == null)
                this.globals.data[this.name] = [];
            this.globals.data[this.name].tabscontent = this.el;
            this.globals.data[this.name].tabscontentElem = this.contentElem;
            this.globals.data[this.name].supertabs = this.supertabs;
            this.globals.initiate(this.name);
            this.supertabs.tabChange.subscribe((/** <==========THIS LINE
             * @param {?} e
             * @return {?}
             */
            e => {
                /** @type {?} */
                let i = e.detail.index;
                /** @type {?} */
                let tabs = this.contentElem.nativeElement.querySelectorAll('super-tab');
                /** @type {?} */
                let results = [];
                for (let tab of tabs) {
                    /** @type {?} */
                    let cont = tab.querySelector('ion-content');
                    if (cont.attributes['hidenav-sh-content'])
                        results.push(cont.attributes['hidenav-sh-content'].nodeValue);
                    else
                        results.push(null);
                }
                if (results[i] != null) {
                    this.globals.resetContent(results[i]);
                }
            }));
        }
    }
    /**
     * @return {?}
     */
    ngOnDestroy() {
        delete this.globals.data[this.name].tabscontent;
    }
}
```
Debugging in chrome, `this.supertabs` is actually undefined.

The following is my component's HTML:

```
<hidenav-stretchheader header-height="90" init-expanded="true" no-border="true">
    <app-custom-header-component></app-custom-header-component>
</hidenav-stretchheader>

<ion-content hidenav-sh-tabscontent>
    <super-tabs [config]="SUPER_TABS_CONFIG">
        <super-tabs-toolbar [showIndicator]="false" slot="top" [scrollable]="true" [scrollablePadding]="false">
            <super-tab-button name="one">ONE</super-tab-button>
            <super-tab-button name="two">TWO</super-tab-button>

            <super-tab-button *ngIf="condition == 'U'" name="three">THREE</super-tab-button>
            <super-tab-button *ngIf="condition == 'U'" name="four">FOUR</super-tab-button>

            <super-tab-button *ngIf="condition == 'V'" name="five">FIVE</super-tab-button>
        </super-tabs-toolbar>
        <super-tabs-container>
            <super-tab>
                <ion-content hidenav-sh-content hidenav-tabspage>
                    <app-custom-component></app-custom-component>
                </ion-content>
            </super-tab>
            <super-tab>
                <ion-content hidenav-sh-content hidenav-tabspage>
                    <app-custom-component></app-custom-component>
                </ion-content>
            </super-tab>

            <super-tab *ngIf="condition == 'U'">
                <ion-content hidenav-sh-content hidenav-tabspage>
                    <app-custom-component></app-custom-component>
                </ion-content>
            </super-tab>
            <super-tab *ngIf="condition == 'U'">
                <ion-content hidenav-sh-content hidenav-tabspage>
                    <app-custom-component></app-custom-component>
                </ion-content>
            </super-tab>

            <super-tab *ngIf="condition == 'V'">
                <ion-content hidenav-sh-content hidenav-tabspage>
                    <app-custom-component></app-custom-component>
                </ion-content>
            </super-tab>

        </super-tabs-container>
    </super-tabs>
</ion-content>
```

And this is the super-tabs configuration:

```
private SUPER_TABS_CONFIG = {
    dragThreshold: 100,
    allowElementScroll: true,
    maxDragAngle: 40,
    sideMenuThreshold: 50,
    transitionDuration: 300,
    shortSwipeDuration: 300,
    debug: true,
    avoidElements: true,
    sideMenu: 'left'
  };
```

I installed super-tabs as a separate package, and I'm noticing that i see two super-tabs in my `npm list` :
```
+-- ionic4-hidenav@0.1.2
| +-- @ionic-super-tabs/angular@6.1.2 <---this one under hidenav
| | +-- @ionic-super-tabs/core@6.1.2
| | `-- tslib@1.10.0 deduped
| +-- jquery@3.4.1
| `-- tslib@1.10.0 deduped
...
+-- @ionic-super-tabs/angular@6.1.3-alpha.1 <---this one as a "standalone" package
| +-- @ionic-super-tabs/core@6.1.3-alpha.1
| `-- tslib@1.10.0 deduped
```

I even tried using version 6.1.2, but the error persists.

Any suggestion? Am i missing something here?

**Comment by heidji** [comment]
Hi, the plug-in hasn't been maintained lately and i need to re-adjust the
packages. will let you know when i do

**Comment by rastafan** [comment]
I'll be waiting then, thank you very much for your prompt response and effort.

**Comment by rastafan** [comment]
Just a heads-up:

it seems to work quite fine with the version included in the node module of this project.

Before i was importing super-tabs like this:

`import { SuperTabsModule } from '@ionic-super-tabs/angular';`

and it was not working (as shown in the original post).
Then I tried importing super-tabs like this:

`import { SuperTabsModule } from 'ionic4-hidenav/node_modules/@ionic-super-tabs/angular';`

and it seems to work.

Hope this helps in updating to the latest version.

**Comment by heidji** [comment]
It is because you're using the outdated version from my project I assume. I will try to update it

**Comment by heidji** [comment]
It seems that the package works out of the box with the new versions of SuperTabs. Just remove that part in tsconfig.json:
```
{
//...
"include": [
    "src",
    "node_modules/@ionic-super-tabs/core/dist/types/interface.d.ts"
  ]
  //...
}
```

**Comment by rastafan** [comment]
Hi,

thanks for your work here.
I'm sorry to bother you again, but i did update ionic4-hidenav to version 0.1.4, then proceeded to remove the tsconfig.json part, and now my project cant seem to find the module.
What i mean is, if i import hidenav into the Shared module as explained in the README (`import { HidenavModule } from 'ionic4-hidenav';`), ionic's build command (and Visual Studio Code) are complaining about the module not being found.
```
ERROR in src/app/shared/shared.module.ts:11:31 - error TS2307: Cannot find module 'ionic4-hidenav'.

11 import { HidenavModule } from 'ionic4-hidenav';
                                 ~~~~~~~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

i then tried importing as `import { HidenavModule } from 'ionic4-hidenav/src/public_api';` but i got more errors, like the following:

```
ERROR in node_modules/ionic4-hidenav/src/lib/hidenav-sh-tabscontent.directive.ts:13:6 - error TS2554: Expected 2 arguments, but got 1.

13     @ContentChild(forwardRef(() => SuperTabs)) supertabs: SuperTabs;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

which i believe is bound to me using ionic 4 - angular 8:

```
Ionic:

   Ionic CLI                     : 5.4.11 (C:\Users\[user]\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1
```

Then i changed all the points where this error came up (not too many), adding `, {static: true}` as the second parameter, and the last error i got on build is this:

```
ERROR in ./node_modules/ionic4-hidenav/src/public_api.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\PATH\TO\PROJECT\node_modules\ionic4-hidenav\src\public_api.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a 
badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\PATH\TO\PROJECT\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:869:23)
    at plugin.done.then (C:\PATH\TO\PROJECT\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Do you happen to know what am i doing wrong? I feel like i'm missing something stupid somewhere but can not see where...

On a side note, i saw that in the example project (https://github.com/heidji/ionic4-hidenav-example) hidenav was imported directly from the app directory. Is that the right place? Or should we keep importing from node_modules?

Thanks again for your hard work.

**Comment by rastafan** [comment]
@heidji bump with tag just to be sure, i do not know if comment's notifications are sent when the issue is closed.

**Comment by heidji** [comment]
normally the plugin should work out of the box, but yes, if it helps, just use the project like in the example repository. sorry for the confusion, i will check what's wrong with the published version when i have some free time again

**Comment by rastafan** [comment]
Thanks again for your prompt response.
I tried using the plugin as it's used in the example and it now seems to be working fine (i just had to `npm install jquery` and `npm install @ionic-super-tabs/angular`).
I guess i'll be good like this for now, i'll keep in touch to let you know if something goes wrong.

Thanks again.

**Comment by heidji** [comment]
I made a big oopsie while publishing v 0.1.4, please install v 0.1.5
